# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
