# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referred_by',
        ),
    ]
